"""
This file demonstrates writing tests using the unittest module. These will pass
when you run "manage.py test".

Replace this with more appropriate tests for your application.
"""

from django.test import TestCase
from blogging.utils import insert_tag_id

class SimpleTest(TestCase):
    def test_basic_addition(self):
        """
        Tests that 1 + 1 always equals 2.
        """
        insert_tag_id('<p style="text-align:justify"><span style="font-size:14px"><span style="font-family:comic sans ms,cursive">A day comes in the life of every programmer when they have to refactor someone else&#39;s code, or their own code, or fix a bug (heck, programmers spend a lot of time debugging someone else&#39;s crap as far as I know) and all hell breaks loose while deadlines tighten their noose around the&nbsp;neck. Here are a few simple practices that one can put to use in order to ease much of the future&nbsp;pain. They&#39;re not specific to any programming language, but generalizations which help keep things clean and less cluttered. They WILL not eliminate all your problems, but assuage it a bit, or perhaps a lot.</span></span></p> \
<ul> <li style="text-align:center"><span style="font-family:comic sans ms,cursive"><span style="color:rgba(0, 0, 0, 0.8); font-size:14px">When writing an interface, method, function or any boundary to a block (a small system),&nbsp;<span style="font-size:16px"><strong>never trust anybody</strong>;</span> not even the future you, or the past you. Simply, don&#39;t assume. There will always be somebody who will disobey interface specifications, if one exists.&nbsp;We all have bad days. <span style="font-size:16px"><em><strong>Always, always, always check data consistency.</strong></em></span></span><br /> \
    <span style="color:rgba(0, 0, 0, 0.8); font-size:14px"><img alt="" src="/static/media/images/2014/06/22/buy-sell.jpg" style="height:589px; width:640px" /></span><br />     <span style="color:rgba(0, 0, 0, 0.8); font-size:14px">(<a href="http://socks-studio.com/img/blog/buy-sell.jpg" target="_blank">Image Source</a>)</span></span></li> \
    <li style="text-align:center"><span style="font-family:comic sans ms,cursive"><span style="color:rgba(0, 0, 0, 0.8); font-size:14px"><span style="font-size:16px"><strong>Document heavily</strong>. </span>No matter if it is absurd, no matter if you&#39;re writing just for yourself, not even if your documentation becomes the butt of meme jokes. Tell yourself what you are doing. <span style="font-size:16px"><strong>Know what you are doing</strong></span> (isn&#39;t that an oxymoron?). Write a symphony, tell a story. Murphy says that an issue will arise the moment you&#39;ve let the memory of the code recede. Murphy did not explicitly say that, but I&#39;m not saying that Murphy did not say that either.&nbsp;</span><br /> \
    <span style="color:rgba(0, 0, 0, 0.8); font-size:14px"><img alt="" src="/static/media/images/2014/06/22/seuss_refactoring.jpg" style="height:443px; width:319px" /></span><br />     <span style="color:rgba(0, 0, 0, 0.8); font-size:14px">(<a href="http://s3.amazonaws.com/giles/092309/uyapgaukdqijirafwmpfwfcww.jpg" target="_blank">Image Credits</a>)</span></span></li> \
    <li style="text-align:center"><span style="font-family:comic sans ms,cursive"><span style="color:rgba(0, 0, 0, 0.8); font-size:14px"><em><strong><span style="font-size:16px">Take what you need, not what you want.</span></strong></em> Especially C coders, I know boilerplate is fun and all, but in the end, if you wanted just the rose, and an elephant came along, holding it in his trunk, you might not satisfy the dependencies. Don&#39;t just include the stdio.h if you will never use it (okay, I&#39;m kidding, you may include it, if you know what you are doing). Besides, you do need a minimal boilerplate in web-design till the point you can make your own.</span><br /> \
    <span style="color:rgba(0, 0, 0, 0.8); font-size:14px"><img alt="" src="/static/media/images/2014/06/22/boilderplatecode-300x284.jpg" style="height:284px; width:300px" /></span><br />     <span style="color:rgba(0, 0, 0, 0.8); font-size:14px">(<a href="https://dublin.zhaw.ch/~stdm/wp-content/uploads/2013/04/BoilderPlateCode.jpg" target="_blank">Image Source</a>)</span></span></li> \
    <li style="text-align:center"><span style="font-family:comic sans ms,cursive"><span style="color:rgba(0, 0, 0, 0.8); font-size:14px">Don&#39;t modularize if a monolith would work. Provided you know what you are doing, always start with a whole, then, depending on the complexity and code reuse factors, break it into smaller reusable wholes. <em><strong><span style="font-size:16px">&quot;</span></strong><span style="font-size:16px"><em><strong>Premature optimization is the root of all evil&quot;</strong></em>.</span></em> Don&#39;t distribute until it starts to become unmanageable. Don&#39;t hold back distribution thinking you can handle anything.</span><br /> \
    <img alt="" src="/static/media/images/2014/06/22/engineers-boat.jpg" style="height:384px; width:417px" /><br /> <span style="font-size:12px">(<a href="http://aestheticblasphemy.com/philosophy/root-all-evil" target="_blank">Image Source</a>)</span></span></li> \
    <li style="text-align:center"><span style="font-family:comic sans ms,cursive"><span style="color:rgba(0, 0, 0, 0.8); font-size:14px">To take care of the above step more effectively, <span style="font-size:16px"><strong>do it on paper first</strong></span> - a pseudo code, verbose descriptions, essays, anything that you are comfortable. Achieve it on paper first (or a notepad) and touch the code screen only when you know what you are going to do it, and how. It has the advantage that design comes first, supporting code comes later, so you&#39;ll see the patterns and methods more clearly. As it goes </span><em><span style="font-size:16px"><strong>&quot;Design is the first sign of human intention&quot;</strong></span>.&nbsp;</em><span style="color:rgba(0, 0, 0, 0.8); font-size:14px">Or else, be prepared to run in circles and come out squares (I don&#39;t know what that means actually).&nbsp;</span><br />\
    <span style="color:rgba(0, 0, 0, 0.8); font-size:14px"><img alt="" src="/static/media/images/2014/06/22/brain_to_paper.jpg" style="height:366px; width:500px" /></span><br />     <a href="http://3.bp.blogspot.com/-W4ICYhq1Alo/TbRtBtQi_3I/AAAAAAAAB8U/U18XywweeFU/s400/tumblr_lbu3munx6L1qzt15co1_400_large.jpg" target="_blank"><span style="color:rgba(0, 0, 0, 0.8); font-size:14px">(Image Source)</span></a></span></li> \
</ul> <p style="text-align:justify"><span style="font-size:14px"><span style="font-family:comic sans ms,cursive">&nbsp;But even after all of this, let it be clear that Software Development Cycle will never cease. You <strong>WILL </strong>have to refactor, there <strong>WILL </strong>be bugs, or feature requests, and you <strong>WILL </strong>have to modify your code. It is called evolution in Darwinian terms, it isn&#39;t meant to be perfect in the first shot, but should be robust and easy to evolve in the long shot. OOPs has &#39;ease of evolution&#39; as one of its core philosophies.</span></span></p> \
',0)
        self.assertEqual(1 + 1, 2)
